---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Order
  labels:
    app: Order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Order
  template:
    metadata:
      labels:
        app: Order
    spec:
      containers:
        - name: Order
          image: username/Order:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Delivery
  labels:
    app: Delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Delivery
  template:
    metadata:
      labels:
        app: Delivery
    spec:
      containers:
        - name: Delivery
          image: username/Delivery:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Stock
  labels:
    app: Stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Stock
  template:
    metadata:
      labels:
        app: Stock
    spec:
      containers:
        - name: Stock
          image: username/Stock:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: CustomerCenter
  labels:
    app: CustomerCenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CustomerCenter
  template:
    metadata:
      labels:
        app: CustomerCenter
    spec:
      containers:
        - name: CustomerCenter
          image: username/CustomerCenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Order
  labels:
    app: Order
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Order


---


apiVersion: v1
kind: Service
metadata:
  name: Delivery
  labels:
    app: Delivery
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Delivery


---


apiVersion: v1
kind: Service
metadata:
  name: Stock
  labels:
    app: Stock
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Stock


---


apiVersion: v1
kind: Service
metadata:
  name: CustomerCenter
  labels:
    app: CustomerCenter
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: CustomerCenter

